"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ar" | "en"
type Direction = "rtl" | "ltr"

interface LanguageContextType {
  language: Language
  direction: Direction
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation objects
const translations = {
  ar: {
    // Common
    "common.shibr": "Shibr",
    "common.coming_soon": "قريباً",
    "common.search": "بحث",
    "common.save": "حفظ",
    "common.language.arabic": "العربية",
    "common.language.english": "English",
    "common.loading": "جاري التحميل...",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.view": "عرض",
    "common.upload": "رفع",
    "common.loading": "جاري التحميل...",
    "common.submit": "إرسال",
    "common.back": "العودة",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.currency": "ريال",
    "common.monthly": "شهرياً",
    "common.july": "يوليو",
    "common.riyadh": "الرياض",
    "common.dammam": "الدمام",

    // Navigation
    "nav.home": "الرئيسية",
    "nav.products": "منتجاتنا",
    "nav.about": "من نحن",
    "nav.services": "الخدمات",
    "nav.contact": "تواصل معنا",
    "nav.blog": "المدونة",
    "nav.signin": "تسجيل الدخول",
    "nav.marketplace": "السوق",
    "nav.dashboard": "لوحة التحكم",
    "nav.navigation": "التنقل",
    "nav.questions": "المسائل والأجوبة",
    "nav.why_us": "لماذا نحن",

    // Dashboard Navigation
    "dashboard.home": "الرئيسية",
    "dashboard.products": "المنتجات",
    "dashboard.shelves": "الرفوف",
    "dashboard.shelves_description": "إدارة الرفوف المتاحة في متجرك",
    
    // Shelves Page
    "shelves.header_description": "تابع حالة كل رف في فروعك، واعرف ما يتأجر المساحات المتاحة لزيادة دخلك بسهولة.",
    "shelves.total_rented_shelves": "إجمالي الرفوف المؤجرة",
    "shelves.total_sales": "إجمالي المبيعات",
    "shelves.available_shelves": "الرفوف المتاحة",
    "shelves.increase_from_last_month": "+20.1% من الشهر الماضي",
    "shelves.your_shelves": "رفوفك",
    "shelves.manage_description": "قم بإدارة رفوفك بسهولة عبر جميع الفروع، تابع حالتها، المؤجرين، ومواعيد التحصيل في مكان واحد.",
    "shelves.display_shelf_now": "اعرض رفك الآن",
    "shelves.search_placeholder": "ابحث باسم المؤجر او مدينة الـ...",
    "shelves.all_filter": "الكل",
    "shelves.rented_shelves_filter": "الرفوف المؤجرة",
    "shelves.available_shelves_filter": "الرفوف المتاحة",
    "shelves.table.shelf_name": "اسم الرف",
    "shelves.table.branch_name": "اسم الفرع",
    "shelves.table.renter": "المؤجر",
    "shelves.table.price": "السعر",
    "shelves.table.status": "الحالة",
    "shelves.table.next_collection": "التحصيل القادم",
    "shelves.table.action": "إجراء",
    "shelves.status.rented": "مؤجر",
    "shelves.status.available": "متاح",
    "shelves.view_details": "عرض التفاصيل",
    
    // Add Shelf
    "add_shelf.title": "أضف رفًا جديدًا لفرع من فروع محلك",
    "add_shelf.description": "🍊 قم بتسجيل مساحة عرض جديدة لتكون متاحة للعلامات التجارية على المنصة، وحدد موقعها، وسعرها، وطريقة تأجيرها",
    "add_shelf.shelf_name": "اسم الرف",
    "add_shelf.shelf_name_placeholder": "رف واجهة",
    "add_shelf.city": "المدينة",
    "add_shelf.city_placeholder": "جدة",
    "add_shelf.branch": "الفرع",
    "add_shelf.branch_placeholder": "جدة",
    "add_shelf.discount_percentage": "النسبة ( على ان لا تزيد عن 22 % )",
    "add_shelf.discount_placeholder": "مثال 5 %",
    "add_shelf.monthly_price": "السعر الشهري",
    "add_shelf.price_placeholder_min": "مثال 500 ريال",
    "add_shelf.price_placeholder_max": "580 ريال",
    "add_shelf.available_from": "متاح من",
    "add_shelf.available_date": "أبريل",
    "add_shelf.rental_duration": "أبعاد الرف",
    "add_shelf.length": "الطول",
    "add_shelf.width": "العرض",
    "add_shelf.depth": "العمق",
    "add_shelf.product_type": "نوع المنتجات المناسبة ( اختياري )",
    "add_shelf.product_type_placeholder": "مثال : كماليس / كوبيات / اجهزة",
    "add_shelf.description_label": "الوصف ( اختياري )",
    "add_shelf.description_placeholder": "مثال : 'كتاب الباب - يمين الداخل'",
    "add_shelf.title_label": "العنوان",
    "add_shelf.location_on_map": "اختر على الخريطة",
    "add_shelf.address": "حطين، الرياض 13512، المملكة العربية السعودية",
    "add_shelf.shelf_images": "صور الرف",
    "add_shelf.upload_shelf_image": "صورة الرف",
    "add_shelf.upload_shelf_image_desc": "حجم الملف لا يزيد عن 10 JPG, PNG or PDF. متكابايت",
    "add_shelf.upload_interior_image": "صورة المحل من الداخل",
    "add_shelf.upload_interior_image_desc": "حجم الملف لا يزيد عن 10 JPG, PNG or PDF. متكابايت",
    "add_shelf.upload_exterior_image": "المحل من الخارج",
    "add_shelf.upload_exterior_image_desc": "حجم الملف لا يزيد عن 10 JPG, PNG or PDF. متكابايت",
    "add_shelf.submit_button": "إرسال الطلب للمراجعة والنشر",
    "add_shelf.price_increase_notice": "السعر سوف يضاف عليه نسبة تتراوح 8%",
    "shelves.new_shelf": "رف جديد",
    "shelves.riyadh_shelf": "رف الرياض",
    "shelves.dammam_shelf": "رف الدمام",
    "dashboard.orders": "الطلبات",
    "dashboard.settings": "الإعدادات",
    "dashboard.profile": "الملف الشخصي",
    "dashboard.posts": "المنشورات",
    "dashboard.stores": "المتاجر",
    "dashboard.payments": "المدفوعات",
    "dashboard.logout": "تسجيل الخروج",
    "dashboard.user.profile": "الملف الشخصي",
    "dashboard.user.settings": "الإعدادات",
    "dashboard.user.name": "اسم المستخدم",
    "dashboard.brand": "لوحة العلامة التجارية",
    "dashboard.store": "لوحة المتجر",
    "dashboard.admin": "لوحة المدير",

    // Dashboard Home Page
    "dashboard.welcome": "مرحبا بك في لوحة التحكم الخاصة بك",
    "dashboard.complete_data": "استكمال البيانات",
    "dashboard.start_displaying_shelves": "ابدأ في عرض رفوفك",
    "dashboard.thanks_for_registering": "شكرا لتسجيلك معنا",
    "dashboard.complete_data_description": "يجب عليك ان تكمل ادخال بياناتك للتمكن من عرض رفوفك للإيجار.",
    "dashboard.incomplete_profile_warning": "تحذير: ملفك الشخصي غير مكتمل",
    "dashboard.complete_profile_now": "أكمل الملف الآن",
    "dashboard.complete_profile_first": "يرجى استكمال بيانات متجرك أولاً",
    "dashboard.manage_store_starts_here": "إدارة محلك تبدأ من هنا",
    "dashboard.display_shelf_now": "اعرض رف الآن",
    "dashboard.monitor_performance_description": "راقب أدائك، اعرض رفوفك للتأجير، وابدأ في زيادة دخلك مع Shelfy.",
    "dashboard.currently_rented_brands": "عدد العلامات المؤجرة حاليا",
    "dashboard.total_sales": "إجمالي المبيعات",
    "dashboard.incoming_orders": "الطلبات الواردة",
    "dashboard.increase_from_last_month": "+20.1% من الشهر الماضي",
    "dashboard.new_rental_requests": "طلبات الإيجار الجديدة",
    "dashboard.see_more": "رؤية المزيد",
    "dashboard.no_rental_requests": "لا يوجد لديك طلبات للإيجار",
    "dashboard.your_shelves": "رفوفك",
    "dashboard.no_shelves_displayed": "ليس لديك رفوف معروضه في الوقت الحالي",
    
    // Admin Dashboard
    "dashboard.control_panel": "لوحة التحكم",
    "dashboard.platform_overview": "نظرة شاملة على أداء المنصة وإحصائياتها",
    "dashboard.total_users": "عدد المستخدمين الكلي",
    "dashboard.from_last_month": "من الشهر الماضي",
    "dashboard.shelves_count": "عدد الرفوف",
    "dashboard.rented": "مؤجر",
    "dashboard.available": "متاح",
    "dashboard.total_revenue": "إجمالي الإيرادات",
    "dashboard.from_rentals": "من عمليات التأجير",
    "dashboard.rental_requests": "طلبات الإيجار",
    "dashboard.revenue_rate": "معدل الإيرادات",
    "dashboard.yearly": "سنوي",
    "dashboard.monthly": "شهري",
    "dashboard.weekly": "أسبوعي",
    "dashboard.daily": "يومي",
    "dashboard.top_selling_products": "أكثر المنتجات مبيعاً",
    "dashboard.increase_by": "ارتفاع بنسبة",
    "dashboard.this_month": "هذا الشهر",
    "dashboard.show_total_turnover": "عرض إجمالي الدوران لفترة الشهر",
    "dashboard.stores_management": "إدارة المحلات",
    "dashboard.store_name": "اسم المحل",
    "dashboard.branch": "الفرع",
    "dashboard.shelf_name": "اسم الرف",
    "dashboard.date_added": "تاريخ الإضافة",
    "dashboard.status": "الحالة",
    "dashboard.options": "خيارات",
    "dashboard.view": "عرض",
    "dashboard.edit": "تعديل",
    "dashboard.reject": "رفض",
    "dashboard.status_under_review": "قيد المراجعة",
    "dashboard.status_accepted": "مقبول",

    // Settings Page
    "settings.title": "الإعدادات",
    "settings.description": "إدارة إعدادات متجرك وحسابك",
    "settings.tabs.general": "عام",
    "settings.tabs.store_data": "بيانات المحل",
    "settings.tabs.payment": "إعدادات الدفع",
    "settings.tabs.branches": "الفروع",
    "settings.tabs.financial": "المالية",
    "settings.tabs.notifications": "الإشعارات",
    "settings.tabs.security": "الأمان",
    
    // General Settings
    "settings.general.title": "الإعدادات العامة",
    "settings.general.description": "معلومات أساسية عن متجرك",
    "settings.general.logo_placeholder": "شعار",
    "settings.general.upload_logo": "رفع شعار المتجر",
    "settings.general.logo_hint": "PNG, JPG حتى 2MB",
    "settings.general.change_photo": "تغيير الصورة",
    "settings.general.basic_info": "المعلومات الأساسية",
    "settings.general.store_name": "اسم المتجر",
    "settings.general.store_name_placeholder": "أدخل اسم متجرك",
    "settings.general.commercial_register": "السجل التجاري",
    "settings.general.commercial_register_placeholder": "رقم السجل التجاري",
    "settings.general.store_type": "نوع المتجر",
    "settings.general.select_store_type": "اختر نوع المتجر",
    "settings.general.types.supermarket": "سوبر ماركت",
    "settings.general.types.pharmacy": "صيدلية",
    "settings.general.types.restaurant": "مطعم",
    "settings.general.types.cafe": "مقهى",
    "settings.general.types.clothing": "ملابس",
    "settings.general.types.electronics": "إلكترونيات",
    "settings.general.types.other": "أخرى",
    "settings.general.establishment_date": "تاريخ التأسيس",
    "settings.general.contact_info": "معلومات الاتصال",
    "settings.general.owner_name": "اسم المالك",
    "settings.general.phone_number": "رقم الهاتف",
    "settings.general.email": "البريد الإلكتروني",
    "settings.general.password": "كلمة المرور",
    "settings.general.website": "الموقع الإلكتروني",
    "settings.general.location_info": "معلومات الموقع",
    "settings.general.country": "الدولة",
    "settings.general.select_country": "اختر الدولة",
    "settings.general.saudi_arabia": "المملكة العربية السعودية",
    "settings.general.city": "المدينة",
    "settings.general.select_city": "اختر المدينة",
    "settings.general.cities.riyadh": "الرياض",
    "settings.general.cities.jeddah": "جدة",
    "settings.general.cities.mecca": "مكة المكرمة",
    "settings.general.cities.medina": "المدينة المنورة",
    "settings.general.cities.dammam": "الدمام",
    "settings.general.cities.khobar": "الخبر",
    "settings.general.full_address": "العنوان الكامل",
    "settings.general.address_placeholder": "الشارع، الحي، رقم المبنى",
    "settings.general.store_description": "وصف المتجر",
    "settings.general.description": "الوصف",
    "settings.general.description_placeholder": "اكتب وصفاً تفصيلياً عن متجرك والخدمات التي تقدمها",
    "settings.general.operating_hours": "ساعات العمل",
    "settings.general.opening_time": "وقت الفتح",
    "settings.general.closing_time": "وقت الإغلاق",
    "settings.general.open_24_hours": "مفتوح 24 ساعة",
    "settings.general.save_changes": "حفظ التغييرات",
    
    // Store Data Settings
    "settings.store_data.store_name": "اسم المتجر",
    "settings.store_data.store_name_placeholder": "أدخل اسم المتجر",
    "settings.store_data.store_type": "نوع العمل",
    "settings.store_data.store_type_placeholder": "اختر نوع العمل",
    "settings.store_data.website": "الموقع الإلكتروني",
    "settings.store_data.website_placeholder": "https://example.com",
    "settings.store_data.commercial_reg": "رقم السجل التجاري",
    "settings.store_data.commercial_reg_placeholder": "أدخل رقم السجل التجاري",
    "settings.store_data.no_commercial_reg": "لا يوجد سجل تجاري ( عمل حر )",
    "settings.store_data.upload_logo": "صورة من المستند",
    "settings.store_data.upload_hint": "حجم الملف لا يزيد عن 10 ميقابايت\nJPG, PNG or PDF",
    "settings.store_data.choose_file": "اختر الملف",
    "settings.store_data.save_changes": "حفظ التغييرات",
    
    // Payment Settings
    "settings.payment.payment_methods_title": "إعدادات الدفع والتحصيل المالي",
    "settings.payment.brand_name": "اسم العلامة التجارية",
    "settings.payment.brand_name_placeholder": "أدخل اسم العلامة التجارية",
    "settings.payment.business_type": "نوع العمل",
    "settings.payment.business_type_placeholder": "اختر نوع العمل",
    "settings.payment.website": "الموقع الإلكتروني",
    "settings.payment.website_placeholder": "https://example.com",
    "settings.payment.commercial_reg": "رقم السجل التجاري",
    "settings.payment.commercial_reg_placeholder": "أدخل رقم السجل التجاري",
    "settings.payment.no_commercial_reg": "لا يوجد سجل تجاري ( عمل حر )",
    "settings.payment.upload_document": "صورة من المستند",
    "settings.payment.upload_hint": "حجم الملف لا يزيد عن 10 ميقابايت\nJPG, PNG or PDF",
    "settings.payment.choose_file": "اختر الملف",
    "settings.payment.save_changes": "حفظ التغييرات",
    "settings.payment.payment_records_title": "إعدادات الدفع والتحصيل المالي",
    "settings.payment.add_payment_method": "إضافة وسيلة دفع",
    "settings.payment.table.date": "التاريخ",
    "settings.payment.table.type": "النوع",
    "settings.payment.table.status": "الحالة",
    "settings.payment.table.details": "التفاصيل",
    "settings.payment.table.method": "طريقة الدفع",
    "settings.payment.table.actions": "خيارات",
    "settings.payment.table.completed": "مكتملة",
    "settings.payment.table.active": "مفعل",
    "settings.payment.table.new_completion": "تحويل بنكي",
    "settings.payment.table.pending_confirmation": "بانتظار التأكيد",
    "settings.payment.payment_records_summary": "سجل عمليات الدفع والتحصيل",
    "settings.payment.summary.date": "التاريخ",
    "settings.payment.summary.history": "التاريخ",
    "settings.payment.summary.type": "النوع",
    "settings.payment.summary.payment_method": "طريقة الدفع",
    "settings.payment.summary.status": "الحالة",
    "settings.payment.summary.actions": "خيارات",
    "settings.payment.summary.download_invoice": "تحميل الفاتورة",
    "settings.payment.summary.schedule_invoice": "دفع الفاتورة",
    "settings.payment.summary.completed": "مكتملة",
    "settings.payment.summary.pending_confirmation": "بانتظار التأكيد",
    "settings.payment.dialog.title": "إضافة طريقة دفع",
    "settings.payment.dialog.select_bank": "اختر البنك",
    "settings.payment.dialog.bank_placeholder": "Al-Rajhi Bank",
    "settings.payment.dialog.account_name": "اسم صاحب الحساب",
    "settings.payment.dialog.account_name_placeholder": "محمد احمد عادل",
    "settings.payment.dialog.account_number": "Bank Card/Account Number",
    "settings.payment.dialog.account_number_placeholder": "من مفضلك أدخل رقم الحساب",
    "settings.payment.dialog.iban": "IBAN",
    "settings.payment.dialog.virtual": "افتراضي",
    "settings.payment.dialog.cancel": "إلغاء",
    "settings.payment.dialog.save": "حفظ التغييرات",
    "settings.payment.active": "مفعل",
    "settings.payment.inactive": "غير مفعل",
    "settings.payment.virtual": "افتراضي",
    "settings.payment.physical": "فعلي",
    "settings.payment.no_payment_methods": "لا توجد طرق دفع",
    "settings.payment.deleted": "تم الحذف",
    "settings.payment.deleted_message": "تم حذف طريقة الدفع بنجاح",
    "settings.payment.error": "خطأ",
    "settings.payment.error_message": "حدث خطأ، يرجى المحاولة مرة أخرى",
    "settings.payment.success": "نجاح",
    "settings.payment.added_message": "تمت إضافة طريقة الدفع بنجاح",
    "settings.payment.validation_error": "خطأ في التحقق",
    "settings.payment.fill_all_fields": "يرجى ملء جميع الحقول المطلوبة",
    "settings.general.success": "نجاح",
    "settings.general.success_message": "تم حفظ الإعدادات العامة بنجاح",
    "settings.general.error": "خطأ",
    "settings.general.error_message": "حدث خطأ أثناء حفظ الإعدادات",
    "settings.general.saving": "جاري الحفظ...",
    "settings.store_data.success": "نجاح",
    "settings.store_data.success_message": "تم حفظ بيانات المتجر بنجاح",
    "settings.store_data.error": "خطأ",
    "settings.store_data.error_message": "حدث خطأ أثناء حفظ بيانات المتجر",
    "settings.store_data.saving": "جاري الحفظ...",
    "settings.store_data.validation_error": "خطأ في التحقق",
    "settings.store_data.fill_required_fields": "يرجى ملء جميع الحقول المطلوبة",
    
    // Branches Settings
    "settings.branches.title": "إدارة الفروع",
    "settings.branches.description": "إدارة فروع متجرك",
    "settings.branches.coming_soon": "قريباً - سيتم إضافة إدارة الفروع",
    "settings.branches.empty_title": "لا توجد فروع حتى الآن",
    "settings.branches.empty_description": "أضف فروعًا لمتجرك لتوسيع نطاق عملك وإدارة مواقع متعددة",
    "settings.branches.add_branch": "إضافة فرع",
    
    // Financial Settings
    "settings.financial.title": "الإعدادات المالية",
    "settings.financial.description": "إدارة الحسابات البنكية والمدفوعات",
    "settings.financial.coming_soon": "قريباً - سيتم إضافة الإعدادات المالية",
    
    // Notifications Settings
    "settings.notifications.title": "إعدادات الإشعارات",
    "settings.notifications.description": "تحكم في الإشعارات التي تتلقاها",
    "settings.notifications.new_rentals": "طلبات الاستئجار الجديدة",
    "settings.notifications.new_rentals_desc": "احصل على إشعار عند وصول طلب استئجار جديد",
    "settings.notifications.sales_updates": "تحديثات المبيعات",
    "settings.notifications.sales_updates_desc": "إشعارات عن المبيعات والإيرادات اليومية",
    "settings.notifications.customer_messages": "رسائل العملاء",
    "settings.notifications.customer_messages_desc": "إشعارات عند وصول رسائل من العملاء",
    "settings.notifications.weekly_reports": "تقارير أسبوعية",
    "settings.notifications.weekly_reports_desc": "احصل على تقرير أسبوعي عن أداء متجرك",
    "settings.notifications.save_changes": "حفظ إعدادات الإشعارات",
    
    // Security Settings
    "settings.security.title": "الأمان وكلمة المرور",
    "settings.security.description": "إدارة أمان حسابك",
    "settings.security.current_password": "كلمة المرور الحالية",
    "settings.security.new_password": "كلمة المرور الجديدة",
    "settings.security.confirm_password": "تأكيد كلمة المرور الجديدة",
    "settings.security.two_factor": "المصادقة الثنائية",
    "settings.security.enable_two_factor": "تفعيل المصادقة الثنائية",
    "settings.security.two_factor_desc": "أضف طبقة حماية إضافية لحسابك",
    "settings.security.save_changes": "حفظ إعدادات الأمان",

    // Shelves Page
    "shelves.title": "إدارة الرفوف",
    "shelves.description": "تأكد للمساحات المعروضة في فروعك",
    "shelves.my_shelves": "رفوفك",
    "shelves.manage_description":
      "قم بإدارة رفوفك بسهولة عبر جميع الفروع تابع حالتها، المؤجرين، ومواعيد التحصيل في مكان واحد",
    "shelves.add_shelf": "اعرض رف الآن",
    "shelves.search_placeholder": "ابحث بإسم المؤجر أو مدينة الفرع ...",
    "shelves.all": "الكل",
    "shelves.available": "الرفوف المتاحة",
    "shelves.rented": "الرفوف المؤجرة",
    "shelves.maintenance": "صيانة",
    "shelves.available_shelves": "الرفوف المتاحة",
    "shelves.total_sales": "إجمالي المبيعات",
    "shelves.total_rented_shelves": "إجمالي الرفوف المؤجرة",

    // Landing Page
    "hero.title": "منصة ذكية تربط بين المتاجر",
    "hero.highlight": "الواقعية والإلكترونية",
    "hero.description":
      "نتطلع إلى مساعدة التجار الراغبين في المتاجر الإلكترونية والمتاجر التجارية الموجودة من خلال نظام واحد وتوفير خدمات وحلول متكاملة لإدارة المخزون وتحديد تحويل المبيعات عبر منصات إلكترونية متعددة",
    "hero.start_now": "ابدأ الآن",
    "hero.learn_more": "تعلم المزيد",
    
    // Features
    "features.title": "ميزاتنا",
    "features.subtitle": "اكتشف كيف تساعدك Shibr في تحقيق أهدافك التجارية",
    "features.clear_rights.title": "حقوق واضحة لكل الأطراف",
    "features.clear_rights.description": "كل منتج مربوط بكود QR خاص، يضمن تتبع كل عملية شراء بدقة، ويعطي كل طرف حقه من العمولة أو الإيراد.",
    "features.empty_spaces.title": "تحويل المساحات الفارغة إلى دخل",
    "features.empty_spaces.description": "لو عندك رف، جدار أو زاوية غير مستخدمة.. Shelfy تساعدك تأجرها وتحقق منها دخل شهري أو نسبة من المبيعات بكل سهولة.",
    "features.real_reach.title": "وصول حقيقي بدون فتح فرع",
    "features.real_reach.description": "لأصحاب المتاجر الإلكترونية، تقدر تحط منتجاتك في أحياء ومدن مختلفة بدون ما تفتح فرع أو توظف أحد.",
    "features.flexible_rental.title": "نظام تأجير مرن",
    "features.flexible_rental.description": "اختر طريقة الدفع المناسبة لك: مبلغ شهري، نسبة من المبيعات، أو مزيج بينهم.. وأنت المتحكم في الشروط.",
    
    // FAQ
    "faq.title": "الأسئلة الشائعة",
    "faq.subtitle": "إجابات على أكثر الأسئلة شيوعاً حول منصة Shibr",
    "faq.q1": "هل Shelfy تأخذ عمولة على كل عملية؟",
    "faq.a1": "نعم ، Shelfy مجرد منصة وسيطة. الاتفاق المالي بالكامل بين صاحب المحل وصاحب المتجر، والمنصة تاخذ نسبة بسيطه.",
    "faq.q2": "هل فيه عقد بين الطرفين؟",
    "faq.a2": "لا يوجد",
    "faq.q3": "كيف يتم تتبع المبيعات؟",
    "faq.a3": "لا يوجد",
    "faq.q4": "هل أقدر أغيّر شروط الإيجار بعد إضافة الرف؟",
    "faq.a4": "لا يوجد",
    "faq.q5": "هل أقدر أستأجر أكثر من محل في نفس الوقت؟",
    "faq.a5": "لا يوجد",
    
    // Footer
    "footer.contact": "تواصل معنا",
    "footer.phone": "+966 50 123 4567",
    "footer.email": "info@shibr.com",
    "footer.address": "الرياض، المملكة العربية السعودية",
    "footer.rights": "جميع الحقوق محفوظة",

    // Shelfy Section
    "shelfy.title": "سواء عندك محل أو متجر إلكتروني...",
    "shelfy.highlight": "Shelfy",
    "shelfy.subtitle": "يربطكم",
    "shelfy.description": "ويفتح لك باب دخل واشتراك في نفس الوقت",
    "shelfy.service_stores": "متاجر الخدمات",
    "shelfy.commercial_centers": "مراكز الخدمة التجارية",
    "shelfy.smart_service": "الخدمة الذكية",
    "shelfy.smart_service_desc": "استقبال طلبات وبيع المنتج",
    "shelfy.fast_service": "الخدمة السريعة",
    "shelfy.fast_service_desc": "خدمة طلبية الأوردر بتحكم كامل - بضع دقائق أو ساعات أو أيام",
    "shelfy.integrated_service": "الخدمة المتكاملة",
    "shelfy.integrated_service_desc": "أنشئ حسابك واشترك وقدم أو اطلب الخدمة المناسبة",
    
    // Commercial Centers
    "shelfy.centers.premium_locations": "مواقع مميزة",
    "shelfy.centers.premium_locations_desc": "أرفف في أفضل المراكز التجارية والمولات الرائدة في المملكة",
    "shelfy.centers.high_traffic": "حركة عالية",
    "shelfy.centers.high_traffic_desc": "معدل زيارات يومي يتجاوز 10,000 زائر في المراكز المختارة",
    "shelfy.centers.targeted_audience": "جمهور مستهدف",
    "shelfy.centers.targeted_audience_desc": "وصول مباشر لشرائح العملاء المناسبة لمنتجاتك",

    // Video Section
    "video.title": "استعرض الحلول المتاحة...",
    "video.highlight": "واختر موقعك القادم",
    "video.description":
      "تطبيق الخدمات المتكاملة في منصة Shelfy يساعد على تحسين الأعمال والتجارة وتوفير الحلول المتكاملة في مكان واحد. يوفر التطبيق التحكم في جميع الأعمال والمبيعات الخدمية المقدمة من خلال منصة واحدة يمكن من خلالها إدارة الأعمال بطريقة احترافية.",
    "video.start_journey": "ابدأ رحلتك الآن",
    "video.jeddah_stores": "جدة - مواقع المتاجر المتاحة",
    "video.riyadh_stores": "الرياض - مواقع المتاجر المتاحة",
    
    // Why Choose Section
    "why_choose.title": "ليش تختار شبر؟ المنصة اللي تجمع بين التجارة الواقعية والرقمية في مكان واحد",
    "why_choose.description": "سواء كنت صاحب محل، تبغى تزيد دخلك، أو متجر إلكتروني تبغى توصل لعملائك في الواقع، Shelfy مصممة تقدم لك تجربة سلسة، مرنة، وتحفظ حقوقك من أول رف إلى آخر بيع.",

    // Statistics
    "stats.why_choose": "ليش تختار",
    "stats.platform": "للمنصة الرقمية",
    "stats.description":
      "الواقعية والرقمية في مكان واحد، منصة Shibr تضم أكثر من 1000 تاجر وأكثر من 10000 منتج وخدمة متنوعة في المملكة العربية السعودية، وتوفر خدمة التوصيل السريع لجميع المناطق في المملكة العربية السعودية.",
    "stats.active_stores": "متجر نشط",
    "stats.happy_customers": "عميل سعيد",
    "stats.sales": "المبيعات",
    "stats.completed_orders": "طلب مكتمل",

    // FAQ
    "faq.title": "أسئلتك المهمة...",
    "faq.highlight": "وحاجاتنا عليها",
    "faq.description": "هنا تجد إجابات على الأسئلة الأكثر شيوعاً حول خدماتنا ومنتجاتنا الإلكترونية",

    // Footer
    "footer.company": "الشركة",
    "footer.about_us": "من نحن",
    "footer.team": "فريق العمل",
    "footer.jobs": "الوظائف",
    "footer.customer_service": "خدمة العملاء",
    "footer.help_center": "مركز المساعدة",
    "footer.privacy_policy": "سياسة الخصوصية",
    "footer.terms": "شروط الاستخدام",
    "footer.contact_us": "تواصل معنا",
    "footer.rights": "جميع الحقوق محفوظة",
    "footer.description":
      "منصة Shibr الرائدة في ربط المتاجر الواقعية والإلكترونية، نوفر حلول متكاملة لإدارة الأعمال التجارية بطريقة احترافية.",
    "footer.social.twitter": "تويتر",
    "footer.social.linkedin": "لينكد إن",

    // Marketplace
    "marketplace.title": "البحث في المحلات والمتاجر",
    "marketplace.search_placeholder": "اكتب اسم المتجر",
    "marketplace.all_cities": "كل المدن",
    "marketplace.all_areas": "كل المناطق",
    "marketplace.riyadh": "الرياض",
    "marketplace.jeddah": "جدة",
    "marketplace.dammam": "الدمام",
    "marketplace.north": "الشمال",
    "marketplace.south": "الجنوب",
    "marketplace.footer.available_stations": "المحطات المتاحة",
    
    // Marketplace Mock Data
    "marketplace.mock.store_name_1": "كوفي سيوت",
    "marketplace.mock.monthly": "شهري",
    "marketplace.mock.location_riyadh": "المملكة العربية السعودية، الرياض 13512، حطين",
    "marketplace.mock.service_type": "نوع الخدمة",
    "marketplace.mock.through_april": "من خلال 1 أبريل",
    "marketplace.east": "الشرق",
    "marketplace.west": "الغرب",
    "marketplace.price_range": "نطاق السعر",
    "marketplace.store_type": "نوع المحل",
    "marketplace.all_types": "جميع الأنواع",
    "marketplace.coffee": "مقاهي",
    "marketplace.restaurant": "مطاعم",
    "marketplace.retail": "متاجر",
    "marketplace.search_stores": "ابحث لمتاجر",
    "marketplace.stores_map": "خريطة المتاجر",
    "marketplace.monthly": "شهري",

    // Auth
    "auth.signin": "تسجيل الدخول",
    "auth.signup": "تسجيل حساب جديد",
    "auth.welcome":
      "مرحبًا بك! سجل دخولك للوصول إلى لوحة التحكم وإدارة نشاطك بكل سهولة، سواء كنت صاحب محل أو متجر إلكتروني.",
    "auth.welcome_back": "مرحباً بعودتك",
    "auth.signin_description": "سجل دخولك للوصول إلى لوحة التحكم وإدارة نشاطك بكل سهولة",
    "auth.dont_have_account": "لا تملك حساباً؟",
    "auth.mobile": "رقم الجوال",
    "auth.password": "كلمة المرور",
    "auth.password_placeholder": "من فضلك أدخل كلمة المرور",
    "auth.remember_me": "تذكرني",
    "auth.forgot_password": "نسيت كلمة المرور؟ استعادة هنا",
    "auth.ready_to_join": "على استعداد للانضمام إلينا؟",
    "auth.already_have_account": "أنت لديك حساب؟",
    "auth.back_to_home": "العودة للرئيسية",
    "auth.create_account": "أنشئ حسابك وابدأ رحلتك مع Shelfy",
    "auth.signup_description":
      "اختر نوع حسابك، وسجّل بياناتك الأساسية، وابدأ في استكشاف فرص الربح أو التوسّع من خلال منصة تربط الواقع بالتجارة الإلكترونية.",
    "auth.account_type": "اختيار نوع الحساب",
    "auth.brand_owner": "صاحب متجر إلكتروني",
    "auth.store_owner": "صاحب محل",
    "auth.name": "الاسم",
    "auth.name_placeholder": "أدخل اسمك بالكامل",
    "auth.email": "البريد الإلكتروني",
    "auth.email_placeholder": "أدخل بريدك الإلكتروني",
    "auth.store_name": "اسم المتجر",
    "auth.brand_name": "اسم العلامة التجارية",
    "auth.store_name_placeholder": "أدخل اسم المتجر",
    "auth.brand_name_placeholder": "أدخل اسم العلامة التجارية",
    "auth.terms_agreement": "بإنشائك حسابك، فإنك توافق على",
    "auth.terms": "الشروط والأحكام",
    "auth.privacy": "سياسة الخصوصية",
    "auth.platform_terms": "الخاصة بمنصة Shelfy",
    "auth.error": "خطأ",
    "auth.success": "نجاح",
    "auth.must_agree_terms": "يجب الموافقة على الشروط والأحكام",
    "auth.account_created_successfully": "تم إنشاء الحساب بنجاح",
    "auth.signup_failed": "فشل إنشاء الحساب. يرجى المحاولة مرة أخرى",
    "auth.signin_success": "تم تسجيل الدخول بنجاح",
    "auth.invalid_credentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة",

    // Orders
    "orders.title": "الطلبات",
    "orders.incoming_title": "طلبات الواردة من المتاجر الإلكترونية",
    "orders.incoming_description":
      "تابع طلبات استئجار الرفوف من المتاجر الإلكترونية، وتابع تفاصيل كل طلب، واتخذ الموافقة أو الرفض بناءً على المعلومات المعروضة.",
    "orders.shipping_title": "طلبات الشحن",
    "orders.shipping_description": "تابع طلبات الشحن من المتاجر الإلكترونية، وتابع تفاصيل كل طلب.",
    "orders.search_placeholder": "ابحث باسم المتجر أو مدينة الفرع",
    "orders.cancel_warning": "سوف يتم إلغاء الطلبات بعد 48 ساعة في حالة عدم الموافقة عليها",
    "orders.all": "الكل",
    "orders.new": "جديد",
    "orders.under_review": "قيد المراجعة",
    "orders.rejected": "مرفوض",
    "orders.accepted": "مقبول",
    "orders.in_transit": "في الطريق",
    "orders.received": "تم الاستلام",
    "orders.store": "المتجر",
    "orders.branch": "الفرع",
    "orders.request_date": "تاريخ الطلب",
    "orders.status": "الحالة",
    "orders.rental_duration": "مدة الايجار",
    "orders.rating": "التقييم",
    "orders.options": "خيارات",
    "orders.view_offer": "عرض",
    "orders.reject": "رفض",
    "orders.accept": "قبول",
    "orders.offer_details": "عرض التفاصيل",
    "orders.month": "شهر",
    "orders.months": "شهور",
    "orders.under_review_badge": "قيد المراجعة",
    "orders.rejected_badge": "مرفوض",

    // Table Headers
    "table.store": "المتجر",
    "table.branch": "الفرع",
    "table.rental_duration": "مدة الإيجار",
    "table.status": "الحالة",
    "table.order_date": "تاريخ الطلب",
    "table.value": "القيمة",
    "table.options": "خيارات",
    "table.shipping_method": "طريقة الشحن",
    "table.incoming_quantity": "الكمية القادمة",
    "table.shelf_name": "اسم الرف",
    "table.location": "الموقع",
    "table.size": "الحجم",
    "table.price": "السعر",
    "table.date_added": "تاريخ الإضافة",

    // Dashboard Stats
    "dashboard.stats.total_shelves": "إجمالي الرفوف",
    "dashboard.stats.active_rentals": "الإيجارات النشطة",
    "dashboard.stats.monthly_revenue": "الإيرادات الشهرية",
    "dashboard.stats.pending_requests": "الطلبات المعلقة",

    // Brand Dashboard
    "brand.dashboard.home": "الرئيسية",
    "brand.dashboard.shelves": "الرفوف",
    "brand.dashboard.products": "المنتجات",
    "brand.dashboard.settings": "الإعدادات",
    "brand.dashboard.welcome": "مرحبا بك في لوحة التحكم الخاصة بك",
    "brand.dashboard.signin": "تسجيل الدخول",
    "brand.dashboard.complete_data": "استكمال البيانات",
    "brand.dashboard.start_renting": "بدأ في الإيجار",
    "brand.dashboard.thanks_for_registering": "شكرا لتسجيلك معنا",
    "brand.dashboard.complete_data_description": "يجب عليك أن تكمل إدخال بياناتك للتمكن من تأجير الرفوف من تاجر الرفوف",
    "brand.dashboard.welcome_to_shelfy": "مرحبا بك في شيلفي",
    "brand.dashboard.monitor_description": "راقب مبيعاتك، الرفوف المؤجرة، المنتجات، وأداء المنتجات بسهولة من مكان واحد",
    "brand.dashboard.rent_new_shelf": "تأجير رف جديد",
    "brand.dashboard.displayed_products_count": "عدد المنتجات المعروضة",
    "brand.dashboard.total_sales": "إجمالي المبيعات",
    "brand.dashboard.rented_shelves_count": "عدد الرفوف المؤجرة حاليا",
    "brand.dashboard.increase_from_last_month": "+20.1% من الشهر الماضي",
    "brand.dashboard.sales": "المبيعات",
    "brand.dashboard.see_more": "رؤية المزيد",
    "brand.dashboard.no_sales_yet": "لا يوجد لديك مبيعات بعد",
    "brand.dashboard.your_rented_shelves": "رفوفك المؤجرة",
    "brand.dashboard.no_shelves_currently": "ليس لديك رفوف في الوقت الحالي",
    "brand.dashboard.add_new_shelf": "إضافة رف جديد",
    "brand.dashboard.latest_sales_operations": "آخر عملياتك البيع",
    "brand.dashboard.no_sales_operations": "لا يوجد لديك عمليات بيع",
  },
  en: {
    // Common
    "common.shibr": "Shibr",
    "common.coming_soon": "Coming Soon",
    "common.search": "Search",
    "common.save": "Save",
    "common.language.arabic": "العربية",
    "common.language.english": "English",
    "common.loading": "Loading...",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.upload": "Upload",
    "common.loading": "Loading...",
    "common.submit": "Submit",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.currency": "SAR",
    "common.monthly": "monthly",
    "common.july": "July",
    "common.riyadh": "Riyadh",
    "common.dammam": "Dammam",

    // Navigation
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.contact": "Contact Us",
    "nav.blog": "Blog",
    "nav.signin": "Sign In",
    "nav.marketplace": "Marketplace",
    "nav.dashboard": "Dashboard",
    "nav.navigation": "Navigation",
    "nav.questions": "Questions & Answers",
    "nav.why_us": "Why Us",

    // Dashboard Navigation
    "dashboard.home": "Home",
    "dashboard.products": "Products",
    "dashboard.shelves": "Shelves",
    "dashboard.shelves_description": "Manage available shelves in your store",
    
    // Shelves Page
    "shelves.header_description": "Track the status of each shelf in your branches, and know what rentable spaces are available to easily increase your income.",
    "shelves.total_rented_shelves": "Total Rented Shelves",
    "shelves.total_sales": "Total Sales",
    "shelves.available_shelves": "Available Shelves",
    "shelves.increase_from_last_month": "+20.1% from last month",
    "shelves.your_shelves": "Your Shelves",
    "shelves.manage_description": "Easily manage your shelves across all branches, track their status, renters, and collection dates in one place.",
    "shelves.display_shelf_now": "Display Your Shelf Now",
    "shelves.search_placeholder": "Search by renter name or city...",
    "shelves.all_filter": "All",
    "shelves.rented_shelves_filter": "Rented Shelves",
    "shelves.available_shelves_filter": "Available Shelves",
    "shelves.table.shelf_name": "Shelf Name",
    "shelves.table.branch_name": "Branch Name",
    "shelves.table.renter": "Renter",
    "shelves.table.price": "Price",
    "shelves.table.status": "Status",
    "shelves.table.next_collection": "Next Collection",
    "shelves.table.action": "Action",
    "shelves.status.rented": "Rented",
    "shelves.status.available": "Available",
    "shelves.view_details": "View Details",
    
    // Add Shelf
    "add_shelf.title": "Add a new shelf for one of your store branches",
    "add_shelf.description": "🍊 Register a new display space to be available for brands on the platform, and specify its location, price, and rental method",
    "add_shelf.shelf_name": "Shelf Name",
    "add_shelf.shelf_name_placeholder": "Front Shelf",
    "add_shelf.city": "City",
    "add_shelf.city_placeholder": "Jeddah",
    "add_shelf.branch": "Branch",
    "add_shelf.branch_placeholder": "Jeddah",
    "add_shelf.discount_percentage": "Percentage (not to exceed 22%)",
    "add_shelf.discount_placeholder": "Example 5%",
    "add_shelf.monthly_price": "Monthly Price",
    "add_shelf.price_placeholder_min": "Example 500 SAR",
    "add_shelf.price_placeholder_max": "580 SAR",
    "add_shelf.available_from": "Available From",
    "add_shelf.available_date": "April",
    "add_shelf.rental_duration": "Shelf Dimensions",
    "add_shelf.length": "Length",
    "add_shelf.width": "Width",
    "add_shelf.depth": "Depth",
    "add_shelf.product_type": "Suitable Product Types (Optional)",
    "add_shelf.product_type_placeholder": "Example: Cosmetics / Cups / Devices",
    "add_shelf.description_label": "Description (Optional)",
    "add_shelf.description_placeholder": "Example: 'Near the door - right side of entrance'",
    "add_shelf.title_label": "Title",
    "add_shelf.location_on_map": "Select on Map",
    "add_shelf.address": "Hittin, Riyadh 13512, Saudi Arabia",
    "add_shelf.shelf_images": "Shelf Images",
    "add_shelf.upload_shelf_image": "Shelf Image",
    "add_shelf.upload_shelf_image_desc": "File size not exceeding 10 MB JPG, PNG or PDF.",
    "add_shelf.upload_interior_image": "Store Interior Image",
    "add_shelf.upload_interior_image_desc": "File size not exceeding 10 MB JPG, PNG or PDF.",
    "add_shelf.upload_exterior_image": "Store Exterior",
    "add_shelf.upload_exterior_image_desc": "File size not exceeding 10 MB JPG, PNG or PDF.",
    "add_shelf.submit_button": "Submit Request for Review and Publishing",
    "add_shelf.price_increase_notice": "Price will be increased by approximately 8%",
    "shelves.new_shelf": "New Shelf",
    "shelves.riyadh_shelf": "Riyadh Shelf",
    "shelves.dammam_shelf": "Dammam Shelf",
    "dashboard.orders": "Orders",
    "dashboard.settings": "Settings",
    "dashboard.profile": "Profile",
    "dashboard.posts": "Posts",
    "dashboard.stores": "Stores",
    "dashboard.payments": "Payments",
    "dashboard.logout": "Logout",
    "dashboard.user.profile": "Profile",
    "dashboard.user.settings": "Settings",
    "dashboard.user.name": "User Name",
    "dashboard.brand": "Brand Dashboard",
    "dashboard.store": "Store Dashboard",
    "dashboard.admin": "Admin Dashboard",

    // Dashboard Home Page
    "dashboard.welcome": "Welcome to your dashboard",
    "dashboard.complete_data": "Complete Data",
    "dashboard.start_displaying_shelves": "Start displaying your shelves",
    "dashboard.thanks_for_registering": "Thank you for registering with us",
    "dashboard.complete_data_description":
      "You must complete entering your data to be able to display your shelves for rent.",
    "dashboard.incomplete_profile_warning": "Warning: Your profile is incomplete",
    "dashboard.complete_profile_now": "Complete Profile Now",
    "dashboard.complete_profile_first": "Please complete your store data first",
    "dashboard.manage_store_starts_here": "Managing your store starts here",
    "dashboard.display_shelf_now": "Display shelf now",
    "dashboard.monitor_performance_description":
      "Monitor your performance, display your shelves for rent, and start increasing your income with Shelfy.",
    "dashboard.currently_rented_brands": "Currently rented brands count",
    "dashboard.total_sales": "Total Sales",
    "dashboard.incoming_orders": "Incoming Orders",
    "dashboard.increase_from_last_month": "+20.1% from last month",
    "dashboard.new_rental_requests": "New rental requests",
    "dashboard.see_more": "See more",
    "dashboard.no_rental_requests": "You have no rental requests",
    "dashboard.your_shelves": "Your shelves",
    "dashboard.no_shelves_displayed": "You have no shelves displayed at the moment",
    
    // Admin Dashboard
    "dashboard.control_panel": "Control Panel",
    "dashboard.platform_overview": "Comprehensive overview of platform performance and statistics",
    "dashboard.total_users": "Total Users",
    "dashboard.from_last_month": "from last month",
    "dashboard.shelves_count": "Shelves Count",
    "dashboard.rented": "rented",
    "dashboard.available": "available",
    "dashboard.total_revenue": "Total Revenue",
    "dashboard.from_rentals": "from rentals",
    "dashboard.rental_requests": "Rental Requests",
    "dashboard.revenue_rate": "Revenue Rate",
    "dashboard.yearly": "Yearly",
    "dashboard.monthly": "Monthly",
    "dashboard.weekly": "Weekly",
    "dashboard.daily": "Daily",
    "dashboard.top_selling_products": "Top Selling Products",
    "dashboard.increase_by": "Increase by",
    "dashboard.this_month": "this month",
    "dashboard.show_total_turnover": "Show total turnover for the month",
    "dashboard.stores_management": "Stores Management",
    "dashboard.store_name": "Store Name",
    "dashboard.branch": "Branch",
    "dashboard.shelf_name": "Shelf Name",
    "dashboard.date_added": "Date Added",
    "dashboard.status": "Status",
    "dashboard.options": "Options",
    "dashboard.view": "View",
    "dashboard.edit": "Edit",
    "dashboard.reject": "Reject",
    "dashboard.status_under_review": "Under Review",
    "dashboard.status_accepted": "Accepted",

    // Settings Page
    "settings.title": "Settings",
    "settings.description": "Manage your store and account settings",
    "settings.tabs.general": "General",
    "settings.tabs.store_data": "Store Data",
    "settings.tabs.payment": "Payment Settings",
    "settings.tabs.branches": "Branches",
    "settings.tabs.financial": "Financial",
    "settings.tabs.notifications": "Notifications",
    "settings.tabs.security": "Security",
    
    // General Settings
    "settings.general.title": "General Settings",
    "settings.general.description": "Basic information about your store",
    "settings.general.logo_placeholder": "Logo",
    "settings.general.upload_logo": "Upload Store Logo",
    "settings.general.logo_hint": "PNG, JPG up to 2MB",
    "settings.general.change_photo": "Change Photo",
    "settings.general.basic_info": "Basic Information",
    "settings.general.store_name": "Store Name",
    "settings.general.store_name_placeholder": "Enter your store name",
    "settings.general.commercial_register": "Commercial Register",
    "settings.general.commercial_register_placeholder": "Commercial register number",
    "settings.general.store_type": "Store Type",
    "settings.general.select_store_type": "Select store type",
    "settings.general.types.supermarket": "Supermarket",
    "settings.general.types.pharmacy": "Pharmacy",
    "settings.general.types.restaurant": "Restaurant",
    "settings.general.types.cafe": "Cafe",
    "settings.general.types.clothing": "Clothing",
    "settings.general.types.electronics": "Electronics",
    "settings.general.types.other": "Other",
    "settings.general.establishment_date": "Establishment Date",
    "settings.general.contact_info": "Contact Information",
    "settings.general.owner_name": "Owner Name",
    "settings.general.phone_number": "Phone Number",
    "settings.general.email": "Email",
    "settings.general.password": "Password",
    "settings.general.website": "Website",
    "settings.general.location_info": "Location Information",
    "settings.general.country": "Country",
    "settings.general.select_country": "Select country",
    "settings.general.saudi_arabia": "Saudi Arabia",
    "settings.general.city": "City",
    "settings.general.select_city": "Select city",
    "settings.general.cities.riyadh": "Riyadh",
    "settings.general.cities.jeddah": "Jeddah",
    "settings.general.cities.mecca": "Mecca",
    "settings.general.cities.medina": "Medina",
    "settings.general.cities.dammam": "Dammam",
    "settings.general.cities.khobar": "Khobar",
    "settings.general.full_address": "Full Address",
    "settings.general.address_placeholder": "Street, District, Building number",
    "settings.general.store_description": "Store Description",
    "settings.general.description": "Description",
    "settings.general.description_placeholder": "Write a detailed description about your store and the services you provide",
    "settings.general.operating_hours": "Operating Hours",
    "settings.general.opening_time": "Opening Time",
    "settings.general.closing_time": "Closing Time",
    "settings.general.open_24_hours": "Open 24 Hours",
    "settings.general.save_changes": "Save Changes",
    
    // Store Data Settings
    "settings.store_data.store_name": "Store Name",
    "settings.store_data.store_name_placeholder": "Enter store name",
    "settings.store_data.store_type": "Business Type",
    "settings.store_data.store_type_placeholder": "Select business type",
    "settings.store_data.website": "Website",
    "settings.store_data.website_placeholder": "https://example.com",
    "settings.store_data.commercial_reg": "Commercial Registration Number",
    "settings.store_data.commercial_reg_placeholder": "Enter commercial registration number",
    "settings.store_data.no_commercial_reg": "No commercial registration (Freelance)",
    "settings.store_data.upload_logo": "Document Image",
    "settings.store_data.upload_hint": "File size up to 10MB\nJPG, PNG or PDF",
    "settings.store_data.choose_file": "Choose File",
    "settings.store_data.save_changes": "Save Changes",
    
    // Payment Settings
    "settings.payment.payment_methods_title": "Payment and Collection Settings",
    "settings.payment.brand_name": "Brand Name",
    "settings.payment.brand_name_placeholder": "Enter brand name",
    "settings.payment.business_type": "Business Type",
    "settings.payment.business_type_placeholder": "Select business type",
    "settings.payment.website": "Website",
    "settings.payment.website_placeholder": "https://example.com",
    "settings.payment.commercial_reg": "Commercial Registration Number",
    "settings.payment.commercial_reg_placeholder": "Enter commercial registration number",
    "settings.payment.no_commercial_reg": "No commercial registration (Freelance)",
    "settings.payment.upload_document": "Document Image",
    "settings.payment.upload_hint": "File size up to 10MB\nJPG, PNG or PDF",
    "settings.payment.choose_file": "Choose File",
    "settings.payment.save_changes": "Save Changes",
    "settings.payment.payment_records_title": "Payment and Collection Settings",
    "settings.payment.add_payment_method": "Add Payment Method",
    "settings.payment.table.date": "Date",
    "settings.payment.table.type": "Type",
    "settings.payment.table.status": "Status",
    "settings.payment.table.details": "Details",
    "settings.payment.table.method": "Payment Method",
    "settings.payment.table.actions": "Actions",
    "settings.payment.table.completed": "Completed",
    "settings.payment.table.active": "Active",
    "settings.payment.table.new_completion": "Bank Transfer",
    "settings.payment.table.pending_confirmation": "Pending Confirmation",
    "settings.payment.payment_records_summary": "Payment and Collection Records",
    "settings.payment.summary.date": "Date",
    "settings.payment.summary.history": "History",
    "settings.payment.summary.type": "Type",
    "settings.payment.summary.payment_method": "Payment Method",
    "settings.payment.summary.status": "Status",
    "settings.payment.summary.actions": "Actions",
    "settings.payment.summary.download_invoice": "Download Invoice",
    "settings.payment.summary.schedule_invoice": "Pay Invoice",
    "settings.payment.summary.completed": "Completed",
    "settings.payment.summary.pending_confirmation": "Pending Confirmation",
    "settings.payment.dialog.title": "Add Payment Method",
    "settings.payment.dialog.select_bank": "Select Bank",
    "settings.payment.dialog.bank_placeholder": "Al-Rajhi Bank",
    "settings.payment.dialog.account_name": "Account Holder Name",
    "settings.payment.dialog.account_name_placeholder": "Mohammed Ahmed Adel",
    "settings.payment.dialog.account_number": "Bank Card/Account Number",
    "settings.payment.dialog.account_number_placeholder": "Please enter account number",
    "settings.payment.dialog.iban": "IBAN",
    "settings.payment.dialog.virtual": "Virtual",
    "settings.payment.dialog.cancel": "Cancel",
    "settings.payment.dialog.save": "Save Changes",
    "settings.payment.active": "Active",
    "settings.payment.inactive": "Inactive",
    "settings.payment.virtual": "Virtual",
    "settings.payment.physical": "Physical",
    "settings.payment.no_payment_methods": "No payment methods",
    "settings.payment.deleted": "Deleted",
    "settings.payment.deleted_message": "Payment method deleted successfully",
    "settings.payment.error": "Error",
    "settings.payment.error_message": "An error occurred, please try again",
    "settings.payment.success": "Success",
    "settings.payment.added_message": "Payment method added successfully",
    "settings.payment.validation_error": "Validation Error",
    "settings.payment.fill_all_fields": "Please fill all required fields",
    "settings.general.success": "Success",
    "settings.general.success_message": "General settings saved successfully",
    "settings.general.error": "Error",
    "settings.general.error_message": "Error saving settings",
    "settings.general.saving": "Saving...",
    "settings.store_data.success": "Success",
    "settings.store_data.success_message": "Store data saved successfully",
    "settings.store_data.error": "Error",
    "settings.store_data.error_message": "Error saving store data",
    "settings.store_data.saving": "Saving...",
    "settings.store_data.validation_error": "Validation Error",
    "settings.store_data.fill_required_fields": "Please fill all required fields",
    
    // Branches Settings
    "settings.branches.title": "Branches Management",
    "settings.branches.description": "Manage your store branches",
    "settings.branches.coming_soon": "Coming Soon - Branches management will be added",
    "settings.branches.empty_title": "No branches yet",
    "settings.branches.empty_description": "Add branches to your store to expand your business and manage multiple locations",
    "settings.branches.add_branch": "Add Branch",
    
    // Financial Settings
    "settings.financial.title": "Financial Settings",
    "settings.financial.description": "Manage bank accounts and payments",
    "settings.financial.coming_soon": "Coming Soon - Financial settings will be added",
    
    // Notifications Settings
    "settings.notifications.title": "Notification Settings",
    "settings.notifications.description": "Control the notifications you receive",
    "settings.notifications.new_rentals": "New Rental Requests",
    "settings.notifications.new_rentals_desc": "Get notified when a new rental request arrives",
    "settings.notifications.sales_updates": "Sales Updates",
    "settings.notifications.sales_updates_desc": "Notifications about daily sales and revenue",
    "settings.notifications.customer_messages": "Customer Messages",
    "settings.notifications.customer_messages_desc": "Notifications when messages arrive from customers",
    "settings.notifications.weekly_reports": "Weekly Reports",
    "settings.notifications.weekly_reports_desc": "Receive a weekly report about your store performance",
    "settings.notifications.save_changes": "Save Notification Settings",
    
    // Security Settings
    "settings.security.title": "Security & Password",
    "settings.security.description": "Manage your account security",
    "settings.security.current_password": "Current Password",
    "settings.security.new_password": "New Password",
    "settings.security.confirm_password": "Confirm New Password",
    "settings.security.two_factor": "Two-Factor Authentication",
    "settings.security.enable_two_factor": "Enable Two-Factor Authentication",
    "settings.security.two_factor_desc": "Add an extra layer of protection to your account",
    "settings.security.save_changes": "Save Security Settings",

    // Shelves Page
    "shelves.title": "Shelf Management",
    "shelves.description": "Confirm spaces displayed in your branches",
    "shelves.my_shelves": "Your Shelves",
    "shelves.manage_description":
      "Easily manage your shelves across all branches, track their status, tenants, and collection dates in one place",
    "shelves.add_shelf": "Display Shelf Now",
    "shelves.search_placeholder": "Search by tenant name or branch city...",
    "shelves.all": "All",
    "shelves.available": "Available Shelves",
    "shelves.rented": "Rented Shelves",
    "shelves.maintenance": "Maintenance",
    "shelves.available_shelves": "Available Shelves",
    "shelves.total_sales": "Total Sales",
    "shelves.total_rented_shelves": "Total Rented Shelves",

    // Landing Page
    "hero.title": "Smart platform connecting",
    "hero.highlight": "physical and online stores",
    "hero.description":
      "We aim to help merchants interested in e-commerce and existing commercial stores through a unified system and provide integrated services and solutions for inventory management and determining sales conversion across multiple electronic platforms",
    "hero.start_now": "Start Now",
    "hero.learn_more": "Learn More",
    
    // Features
    "features.title": "Our Features",
    "features.subtitle": "Discover how Shibr helps you achieve your business goals",
    "features.clear_rights.title": "Clear Rights for All Parties",
    "features.clear_rights.description": "Each product is linked to a unique QR code, ensuring accurate tracking of every purchase and giving each party their rightful commission or revenue.",
    "features.empty_spaces.title": "Turn Empty Spaces into Income",
    "features.empty_spaces.description": "If you have an unused shelf, wall, or corner, Shelfy helps you rent it out and generate monthly income or a percentage of sales easily.",
    "features.real_reach.title": "Real Reach Without Opening a Branch",
    "features.real_reach.description": "For online store owners, you can place your products in different neighborhoods and cities without opening a branch or hiring anyone.",
    "features.flexible_rental.title": "Flexible Rental System",
    "features.flexible_rental.description": "Choose the payment method that suits you: monthly amount, percentage of sales, or a mix of both. You're in control of the terms.",
    
    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Answers to the most common questions about Shibr platform",
    "faq.q1": "Does Shelfy take a commission on every transaction?",
    "faq.a1": "Yes, Shelfy is just an intermediary platform. The financial agreement is entirely between the store owner and the merchant, and the platform takes a small percentage.",
    "faq.q2": "Is there a contract between the parties?",
    "faq.a2": "Not available",
    "faq.q3": "How are sales tracked?",
    "faq.a3": "Not available",
    "faq.q4": "Can I change the rental terms after adding the shelf?",
    "faq.a4": "Not available",
    "faq.q5": "Can I rent more than one store at the same time?",
    "faq.a5": "Not available",
    
    // Footer
    "footer.contact": "Contact Us",
    "footer.phone": "+966 50 123 4567",
    "footer.email": "info@shibr.com",
    "footer.address": "Riyadh, Saudi Arabia",
    "footer.rights": "All rights reserved",

    // Shelfy Section
    "shelfy.title": "Whether you have a store or an online shop...",
    "shelfy.highlight": "Shelfy",
    "shelfy.subtitle": "connects you",
    "shelfy.description": "and opens the door to income and participation at the same time",
    "shelfy.service_stores": "Service Stores",
    "shelfy.commercial_centers": "Commercial Service Centers",
    "shelfy.smart_service": "Smart Service",
    "shelfy.smart_service_desc": "Receive orders and sell products",
    "shelfy.fast_service": "Fast Service",
    "shelfy.fast_service_desc": "Order service with full control - minutes, hours or days",
    "shelfy.integrated_service": "Integrated Service",
    "shelfy.integrated_service_desc": "Create your account, subscribe and provide or request the appropriate service",
    
    // Commercial Centers
    "shelfy.centers.premium_locations": "Premium Locations",
    "shelfy.centers.premium_locations_desc": "Shelves in the best commercial centers and leading malls in the Kingdom",
    "shelfy.centers.high_traffic": "High Traffic",
    "shelfy.centers.high_traffic_desc": "Daily visitor rate exceeding 10,000 visitors in selected centers",
    "shelfy.centers.targeted_audience": "Targeted Audience",
    "shelfy.centers.targeted_audience_desc": "Direct access to customer segments suitable for your products",

    // Video Section
    "video.title": "Explore available solutions...",
    "video.highlight": "and choose your next location",
    "video.description":
      "The integrated services application on the Shelfy platform helps improve business and commerce and provide integrated solutions in one place. The application provides control over all business and service sales provided through one platform through which business can be managed professionally.",
    "video.start_journey": "Start Your Journey Now",
    "video.jeddah_stores": "Jeddah - Available store locations",
    "video.riyadh_stores": "Riyadh - Available store locations",
    
    // Why Choose Section
    "why_choose.title": "Why choose Shibr? The platform that brings together physical and digital commerce in one place",
    "why_choose.description": "Whether you're a store owner looking to increase your income, or an online store wanting to reach customers in reality, Shelfy is designed to provide you with a smooth, flexible experience that preserves your rights from the first shelf to the last sale.",

    // Statistics
    "stats.why_choose": "Why choose",
    "stats.platform": "for the digital platform",
    "stats.description":
      "Physical and digital in one place, Shibr platform includes more than 1000 merchants and more than 10000 diverse products and services in Saudi Arabia, and provides fast delivery service to all regions in Saudi Arabia.",
    "stats.active_stores": "Active Stores",
    "stats.happy_customers": "Happy Customers",
    "stats.sales": "Sales",
    "stats.completed_orders": "Completed Orders",

    // FAQ
    "faq.title": "Your important questions...",
    "faq.highlight": "and our answers to them",
    "faq.description":
      "Here you will find answers to the most frequently asked questions about our services and electronic products",

    // Footer
    "footer.company": "Company",
    "footer.about_us": "About Us",
    "footer.team": "Team",
    "footer.jobs": "Jobs",
    "footer.customer_service": "Customer Service",
    "footer.help_center": "Help Center",
    "footer.privacy_policy": "Privacy Policy",
    "footer.terms": "Terms of Use",
    "footer.contact_us": "Contact Us",
    "footer.rights": "All rights reserved",
    "footer.description":
      "Shibr platform is a leader in connecting physical and online stores, providing integrated solutions for managing commercial business professionally.",
    "footer.social.twitter": "Twitter",
    "footer.social.linkedin": "LinkedIn",

    // Marketplace
    "marketplace.title": "Search Stores and Markets",
    "marketplace.search_placeholder": "Type store name",
    "marketplace.all_cities": "All Cities",
    "marketplace.all_areas": "All Areas",
    "marketplace.riyadh": "Riyadh",
    "marketplace.jeddah": "Jeddah",
    "marketplace.dammam": "Dammam",
    "marketplace.north": "North",
    "marketplace.south": "South",
    "marketplace.footer.available_stations": "Available Stations",
    
    // Marketplace Mock Data
    "marketplace.mock.store_name_1": "Coffee Suit",
    "marketplace.mock.monthly": "Monthly",
    "marketplace.mock.location_riyadh": "Saudi Arabia, Riyadh 13512, Hittin",
    "marketplace.mock.service_type": "Service Type",
    "marketplace.mock.through_april": "Through April 1",
    "marketplace.east": "East",
    "marketplace.west": "West",
    "marketplace.price_range": "Price Range",
    "marketplace.store_type": "Store Type",
    "marketplace.all_types": "All Types",
    "marketplace.coffee": "Coffee Shops",
    "marketplace.restaurant": "Restaurants",
    "marketplace.retail": "Retail Stores",
    "marketplace.search_stores": "Search Stores",
    "marketplace.stores_map": "Stores Map",
    "marketplace.monthly": "Monthly",

    // Auth
    "auth.signin": "Sign In",
    "auth.signup": "Create New Account",
    "auth.welcome":
      "Welcome! Sign in to access your dashboard and manage your activity easily, whether you are a store owner or an online store.",
    "auth.welcome_back": "Welcome Back",
    "auth.signin_description": "Sign in to access your dashboard and manage your activity easily",
    "auth.dont_have_account": "Don't have an account?",
    "auth.mobile": "Mobile Number",
    "auth.password": "Password",
    "auth.password_placeholder": "Please enter your password",
    "auth.remember_me": "Remember me",
    "auth.forgot_password": "Forgot password? Recover here",
    "auth.ready_to_join": "Ready to join us?",
    "auth.already_have_account": "Already have an account?",
    "auth.back_to_home": "Back to Home",
    "auth.create_account": "Create your account and start your journey with Shelfy",
    "auth.signup_description":
      "Choose your account type, register your basic information, and start exploring profit or expansion opportunities through a platform that connects reality with e-commerce.",
    "auth.account_type": "Choose Account Type",
    "auth.brand_owner": "Online Store Owner",
    "auth.store_owner": "Store Owner",
    "auth.name": "Name",
    "auth.name_placeholder": "Enter your full name",
    "auth.email": "Email",
    "auth.email_placeholder": "Enter your email address",
    "auth.store_name": "Store Name",
    "auth.brand_name": "Brand Name",
    "auth.store_name_placeholder": "Enter store name",
    "auth.brand_name_placeholder": "Enter brand name",
    "auth.terms_agreement": "By creating your account, you agree to the",
    "auth.terms": "Terms and Conditions",
    "auth.privacy": "Privacy Policy",
    "auth.platform_terms": "of Shelfy platform",
    "auth.error": "Error",
    "auth.success": "Success",
    "auth.must_agree_terms": "You must agree to the terms and conditions",
    "auth.account_created_successfully": "Account created successfully",
    "auth.signup_failed": "Failed to create account. Please try again",
    "auth.signin_success": "Signed in successfully",
    "auth.invalid_credentials": "Invalid email or password",

    // Orders
    "orders.title": "Orders",
    "orders.incoming_title": "Incoming Orders from Online Stores",
    "orders.incoming_description":
      "Track shelf rental orders from online stores, follow up on each order details, and make approval or rejection decisions based on the displayed information.",
    "orders.shipping_title": "Shipping Orders",
    "orders.shipping_description": "Track shipping orders from online stores and follow up on each order details.",
    "orders.search_placeholder": "Search by store name or branch city",
    "orders.cancel_warning": "Orders will be cancelled after 48 hours if not approved",
    "orders.all": "All",
    "orders.new": "New",
    "orders.under_review": "Under Review",
    "orders.rejected": "Rejected",
    "orders.accepted": "Accepted",
    "orders.in_transit": "In Transit",
    "orders.received": "Received",
    "orders.store": "Store",
    "orders.branch": "Branch",
    "orders.request_date": "Request Date",
    "orders.status": "Status",
    "orders.rental_duration": "Rental Duration",
    "orders.rating": "Rating",
    "orders.options": "Options",
    "orders.view_offer": "View",
    "orders.reject": "Reject",
    "orders.accept": "Accept",
    "orders.offer_details": "View Details",
    "orders.month": "month",
    "orders.months": "months",
    "orders.under_review_badge": "Under Review",
    "orders.rejected_badge": "Rejected",

    // Table Headers
    "table.store": "Store",
    "table.branch": "Branch",
    "table.rental_duration": "Rental Duration",
    "table.status": "Status",
    "table.order_date": "Order Date",
    "table.value": "Value",
    "table.options": "Options",
    "table.shipping_method": "Shipping Method",
    "table.incoming_quantity": "Incoming Quantity",
    "table.shelf_name": "Shelf Name",
    "table.location": "Location",
    "table.size": "Size",
    "table.price": "Price",
    "table.date_added": "Date Added",

    // Dashboard Stats
    "dashboard.stats.total_shelves": "Total Shelves",
    "dashboard.stats.active_rentals": "Active Rentals",
    "dashboard.stats.monthly_revenue": "Monthly Revenue",
    "dashboard.stats.pending_requests": "Pending Requests",

    // Brand Dashboard
    "brand.dashboard.home": "Home",
    "brand.dashboard.shelves": "Shelves",
    "brand.dashboard.products": "Products",
    "brand.dashboard.settings": "Settings",
    "brand.dashboard.welcome": "Welcome to your dashboard",
    "brand.dashboard.signin": "Sign In",
    "brand.dashboard.complete_data": "Complete Data",
    "brand.dashboard.start_renting": "Start Renting",
    "brand.dashboard.thanks_for_registering": "Thank you for registering with us",
    "brand.dashboard.complete_data_description": "You must complete entering your data to be able to rent shelves from shelf merchants",
    "brand.dashboard.welcome_to_shelfy": "Welcome to Shelfy",
    "brand.dashboard.monitor_description": "Monitor your sales, rented shelves, products, and product performance easily from one place",
    "brand.dashboard.rent_new_shelf": "Rent New Shelf",
    "brand.dashboard.displayed_products_count": "Displayed Products Count",
    "brand.dashboard.total_sales": "Total Sales",
    "brand.dashboard.rented_shelves_count": "Currently Rented Shelves Count",
    "brand.dashboard.increase_from_last_month": "+20.1% from last month",
    "brand.dashboard.sales": "Sales",
    "brand.dashboard.see_more": "See More",
    "brand.dashboard.no_sales_yet": "You have no sales yet",
    "brand.dashboard.your_rented_shelves": "Your Rented Shelves",
    "brand.dashboard.no_shelves_currently": "You have no shelves at the moment",
    "brand.dashboard.add_new_shelf": "Add New Shelf",
    "brand.dashboard.latest_sales_operations": "Your Latest Sales Operations",
    "brand.dashboard.no_sales_operations": "You have no sales operations",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar")
  const direction: Direction = language === "ar" ? "rtl" : "ltr"

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
    // Update document direction
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "ar" || savedLanguage === "en")) {
      setLanguageState(savedLanguage)
      document.documentElement.dir = savedLanguage === "ar" ? "rtl" : "ltr"
      document.documentElement.lang = savedLanguage
    }
  }, [])

  return <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
